### ISSUE TITLE
Thanks Dude! Now my M560 doesn't work at all anymore

### ISSUE THREAD

**Issue by alindl** [CzBiX/logitech-m560#1]
Using Linux Mint btw

**Comment by CzBiX** [comment]
The patch for m560 already merged into kernel v4.2.
And make sure you checkout the right version before use: [commits](https://github.com/CzBiX/logitech-m560/commits/m545).

**Comment by alindl** [comment]
I used your branch for m560 because this branch doesn't even compile.

> /logitech-m560-m545/hid-logitech-hidpp.c:1149:3: error: implicit declaration of function ‘hid_field_extract’ [-Werror=implicit-function-declaration]
>    v = hid_snto32(hid_field_extract(hdev, data+3, 0, 12), 12);
>    ^

Btw after `make uninstall` and reboot it "worked" again with silly thumb key functions.

Sorry for the aggressive thread name, I'm looking for a solution to use the thumb buttons as they usually work and tried too many of those "easy solutions" to this problem, and none of them work.

**Comment by CzBiX** [comment]
The m560 branch didn't update for a long time.
And what's your kernel version, please check it before use.

**Comment by alindl** [comment]
Linux Mint 17.3
Kernel: 3.19.0-32-generic
14.04.1-Ubuntu

**Comment by CzBiX** [comment]
I just checkout 5e76291c65fce0220cdc8904462e3869b4e52d73, and compile it for `3.19.0-51-generic` on Ubuntu 14.04 without problem.

**Comment by alindl** [comment]
You are my personal hero of the day :+1:

**Comment by CzBiX** [comment]
Glad helped you.
